import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { CarritoProvider } from "@/context/CarritoContext"; // Asegúrate de que la ruta es correcta
import { BodegaProvider } from "@/context/BodegaContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Punto de venta stock",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><BodegaProvider>
        <CarritoProvider> {/* Envolver toda la aplicación */}
          <Header />
          {children}
        </CarritoProvider>
        </BodegaProvider>
      </body>
    </html>
  );
}
