import "./globals.css";
import Header from "@/components/Header";
import { CarritoProvider } from "@/context/CarritoContext";
import { BodegaProvider } from "@/context/BodegaContext";
import { AuthProvider } from "@/context/AuthContext";

export const metadata = {
    title: "Punto de venta stock",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className="antialiased">
                <AuthProvider>
                    <BodegaProvider>
                        <CarritoProvider>
                            <Header />
                            {children}
                        </CarritoProvider>
                    </BodegaProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
